services:
  - type: web
    name: ecommerce-backend
    env: node
    buildCommand: cd api && npm install
    startCommand: cd api && npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
